### ISSUE TITLE
How to show django errors, using {% bootstrap_field  %} ?

### ISSUE THREAD

**Issue by fhbash** [zostera/django-bootstrap3#104]
Hi, I have this code:

``` html
<div class="row">
                            <div class="col-sm-4">
                                {% bootstrap_field form.bairro_entrega %}
                            </div>
                            <div class="col-sm-4">
                                {% bootstrap_field form.cidade_entrega %}
                            </div>
                            <div class="col-sm-2">
                                {% bootstrap_field form.cep_entrega %}
                            </div>
</div>
```

All 3 fields are required. When I click on submit, the browser go to the first empty field, ok.. it`s great! but doesn`t show any message. How can I show a message to the user?

Cheers

**Comment by BrigitteMaillere** [comment]
Hi, doesn't work for me with fresh install of django-bootstrap3-develop, django 1.11, Python 3.4, 

![image](https://user-images.githubusercontent.com/9556144/28266600-072b0772-6af6-11e7-8860-80146e654fc7.png)
