### ISSUE TITLE
Is it possible to create a horizontal inline form?

### ISSUE THREAD

**Issue by keith-g** [zostera/django-bootstrap3#136]
I looked at the examples and tried to use different permutations like 'layout="inline horizontal"', but couldn't find anything that resembles this use case.

Am I missing something?

**Comment by jaddison** [comment]
For full forms, they're mutually exclusive yes.  But you should be able to inline a couple of fields within a horizontal form - ie. in a credit card form expire month and year are commonly inlined.  Here's an example from http://stackoverflow.com/a/12212196/382774:

```
<form class="form-horizontal" role="form">
    <div class="form-group">
      <label for="inputType" class="col-md-2 control-label">Type</label>
      <div class="col-md-3">
          <input type="text" class="form-control" id="inputType" placeholder="Type">
      </div>
    </div>
    <div class="form-group">
        <span class="col-md-2 control-label">Metadata</span>
        <div class="col-md-6">
            <div class="form-group row">
                <label for="inputKey" class="col-md-1 control-label">Key</label>
                <div class="col-md-2">
                    <input type="text" class="form-control" id="inputKey" placeholder="Key">
                </div>
                <label for="inputValue" class="col-md-1 control-label">Value</label>
                <div class="col-md-2">
                    <input type="text" class="form-control" id="inputValue" placeholder="Value">
                </div>
            </div>
        </div>
    </div>
</form>
```

I'm facing this exactly situation with a credit card form. Have I missed something, or is this not supported by django-bootstrap3?

**Comment by jaddison** [comment]
Ok, ignore my comment! You can just add `form_group_class=''` to the desired `bootstrap_field` tag. The `form-group` class won't be added then.
