### ISSUE TITLE
Horizontal form with buttons 

### ISSUE THREAD

**Issue by mociepka** [zostera/django-bootstrap3#23]
I try to get horizontal form that will be looks like form from [bootstrap guide](http://getbootstrap.com/css/#forms-horizontal). I used:

``` django
{% bootstrap_form form layout='horizontal' %}
{% buttons %}
    {% bootstrap_button 'Sign in' 'submit' %}
{% endbuttons %}
```

![52580b612f7cc62e26000024](https://f.cloud.github.com/assets/1870738/1315091/a4251222-3281-11e3-86d4-409d0495e4f4.jpeg)

But the button is in the wrong position.

Is there any `horizontal` option for the `bootstrap_button` templatetag? How can I achieve that?

**Comment by doganmeh** [comment]
> Try 'buttons layout="horizontal"'

This behavior does not seem to be documented. Should it be?
