### ISSUE TITLE
Settings does not respect the Django Test tools

### ISSUE THREAD

**Issue by cybojenix** [zostera/django-bootstrap3#388]
Since settings is cached, it should be reloaded during tests when this signal is sent:
https://docs.djangoproject.com/en/1.10/ref/signals/#django.test.signals.setting_changed

bumped into this one while writing a test case, to check the behaviour of placeholders

**Comment by jieter** [comment]
@cybojenix thanks for reporting this issue. Are you able to provide a PR proposing a fix for this issue?

**Comment by cybojenix** [comment]
Unfortunately, not at this time. Sorry

**Comment by dyve** [comment]
Caching settings is not such a good idea. I agree this is a bug and should be fixed. Priority is not super high, since it only hits edge cases where settings are changed when the app is running.

**Comment by jieter** [comment]
Ping

**Comment by dyve** [comment]
I may have just fixed this, but without a testcase it is hard to check.

**Comment by dyve** [comment]
Fixed in #481
