### ISSUE TITLE
Improve error reporting for missing fields passed to bootstrap_field

### ISSUE THREAD

**Issue by jieter** [zostera/django-bootstrap3#437]
If I accidentally remove a field from a form, but still try to render it using `{% bootstrap_field`, I get an error message which doesn't really help me to track down my error:

`bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.`

It would be nice if the error message could be more informative.

**Comment by jieter** [comment]
I'd still like to improve this

**Comment by npdnben** [comment]
Here's a temporary solution that makes the exception message helpful:
https://stackoverflow.com/a/74841736/700444

**Comment by dyve** [comment]
No further changes are expected on this project. See README.md (https://github.com/zostera/django-bootstrap3/pull/964 ).
