### ISSUE TITLE
cannot create floating labels

### ISSUE THREAD

**Issue by hayate** [zostera/django-bootstrap3#626]
It seems impossible to create a bootstrap form with floating labels as shown below because:

1. when using the `bootstrap_field` tag only, the label is rendered before the input tag, this breaks floating labels
2. when using separate `bootstrap_field` and `bootstrap_label` tags, the input field is wrapped in a div that breaks floating labels. 

```html
<div class="form-floating mb-3">
  <input type="email" class="form-control" id="floatingInput" placeholder="Username">
  <label for="floatingInput">Email address</label>
</div>
<div class="form-floating">
  <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
  <label for="floatingPassword">Password</label>
</div>
```

**Comment by CleitonDeLima** [comment]
@hayate Hi
I think floating labels is from bootstrap 4, right?

**Comment by hayate** [comment]
@CleitonDeLima sorry for the late reply. I am not sure, I rarely venture into the front-end. It's possible that they were not in the previous version of bootstrap.

**Comment by dyve** [comment]
No further changes are expected on this project. See README.md (#964 ).
