### ISSUE TITLE
django messages framework message tags

### ISSUE THREAD

**Issue by radzhome** [zostera/django-bootstrap3#72]
the old bootstrap2 had a 1-1 mapping with django messages, so you could write:
class= {{message.tags }}-alert

Now 'error' changed to 'danger' in bs3, so any way this app can compensate for that? I added it manually. Is that the best way to handle that or could you squeeze this in to this app? 

```
    {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }} {% if message.tags = 'error' %}alert-danger{%endif%}"{% endif %}>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message|safe }}
        </div>
    {% endfor %}
```

**Comment by beruic** [comment]
I think this one has to be reopened. If you override in `MESSAGE_TAGS` the level id displayed wrong in the admin panel. Furthermore, you should use `message.level_tag` instead of `message.tags` because `message.tags` could be `'customtag warning'`.
