### ISSUE TITLE
[Feature] Input groups

### ISSUE THREAD

**Issue by joekrie** [zostera/django-bootstrap3#73]
Unless I'm missing something, there isn't any support for input group addons in this version (http://getbootstrap.com/components/#input-groups). It appears that there was in the old version of this (https://github.com/dyve/django-bootstrap-toolkit/blob/master/bootstrap_toolkit/templates/bootstrap_toolkit/field_prepend_append.html).

**Comment by Onset** [comment]
@lardissone I have the same question. Have you figured it out yet?

**Comment by lardissone** [comment]
@Onset sorry, I don't know how I've resolved it. Haven't used this project for long time now.

**Comment by Onset** [comment]
No worries. Thank you for your response.
