### ISSUE TITLE
Inline form field errors not displayed

### ISSUE THREAD

**Issue by karolpivo** [zostera/django-bootstrap3#81]
Hi,

field errors are not displayed in inline forms. 

I traced it down to line 45 in forms.py. 

```
    if field.is_hidden and field.errors:
        errors += field.errors
```

It seems that only errors of hidden fields are displayed. I removed the "field.is_hidden" from the if statement and the errors are now displayed.

cheers

**Comment by mmattdugan** [comment]
I have not noticed field errors are shown as title until I came to this page. Tooltips on a input field are not shown if you click on them. You have to hover your mouse over them and wait about a second (which most people don't). So, I don't think this behavior is good as it is. 

From another perspective, my inline form fields are stacked vertically and field errors show nicely under each (if enabled). Therefore, I think showing field errors as usual should be the default behavior and there should be an option for having them as the title attribute (if necessary). At the least, showing field errors should be optional. 

Also, I noticed inline forms do not show messages on top (i.e., password mismatch). I should create a bug report for this separately?
